# Generated by Django 5.2.8 on 2025-12-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_favorited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
